// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPJV_y3KhVYyuOHqi3dcULxM4iLDv8GM',
    appId: '1:650308617054:web:45741c1a1969ba4ccc05cf',
    messagingSenderId: '650308617054',
    projectId: 'mobile-f4f60',
    authDomain: 'mobile-f4f60.firebaseapp.com',
    storageBucket: 'mobile-f4f60.firebasestorage.app',
    measurementId: 'G-SRP4PZ350W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANGKaFJ9lLrRNHrcvdHHpzbPaz6-Rr9Bk',
    appId: '1:650308617054:android:d7e0349a15996493cc05cf',
    messagingSenderId: '650308617054',
    projectId: 'mobile-f4f60',
    storageBucket: 'mobile-f4f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-2m4Yc8yRzhLQ5UvnaUInQQNryxMBQU',
    appId: '1:650308617054:ios:f05e02c699e36f0ecc05cf',
    messagingSenderId: '650308617054',
    projectId: 'mobile-f4f60',
    storageBucket: 'mobile-f4f60.firebasestorage.app',
    iosBundleId: 'com.redahamouch.controle',
  );

}